services:
  postgres:
    image: postgres
    command: postgres -c 'max_connections=100'
    container_name: wmelon-db
    environment:
      POSTGRES_DB: wmelon
      POSTGRES_USER: olzhas
      POSTGRES_PASSWORD: 4chert
      PGDATA: /data/postgres
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5555:5432
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "10"
